### PR TITLE
feat(networks): update genesis.json

### PR DESCRIPTION
**Pull request by Sen-Com**
## Description and Motivation

Modifies draft of genesis file

---
## Checklist:

- [x] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-chain/blob/main/docs/CONTRIBUTING.md).
- [x] My pull request has a sound title and description (not something vague like `Update index.md`)
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation.
- [x] The code is formatted properly `go fmt path/to/your/package`.

### CODE REVIEW

**Comment by faddat** [comment]
note: this may need to change a bit because of alliance, not sure.

**Comment by faddat** [comment]
to ensure valid:

```bash
migalood validate-genesis networks/planning/genesis.json
```

gn

**Review by kerber0x — APPROVED** [review]
:shipit:

**Review by kerber0x — CHANGES_REQUESTED** [review]
The genesis file looks good, it's valid. Let's add `.DS_Store` files to .gitignore so we don't get those popping up in our PRs.

**Pull request merged**
