### PR TITLE
remove starport config and try to fix default bond denom

### PR DESCRIPTION
**Pull request by faddat**
## Description and Motivation

An attempt at fixing the default bond denom and closing that outstanding issue.

## Related Issues

---
## Checklist:

- [ ] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-chain/blob/main/docs/CONTRIBUTING.md).
- [ ] My pull request has a sound title and description (not something vague like `Update index.md`)
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation.
- [ ] The code is formatted properly `golangci-lint run ./... --fix`.

### CODE REVIEW

**Comment by faddat** [comment]
darn.  This is an issue on stride too.  (the issue with the broken ci you can see here) -- will look into fixes and revert.

**Review by pysel — APPROVED** [review]
lgtm when ci passes!

**Review by hieuvubk — APPROVED** [review]

**Comment by faddat** [comment]
@pysel @hieuvubk @DongLieu can you guys please try and get this one passing tests?

**Comment by hieuvubk** [comment]
> @pysel @hieuvubk @DongLieu can you guys please try and get this one passing tests?

I'm on it

**Comment by faddat** [comment]
thank you!

**Review by hieuvubk — APPROVED** [review]

**Comment by faddat** [comment]
@hieuvubk the branch needs signed commits only, can you please enable signed commits in github and also enable vigilant mode?

**Comment by faddat** [comment]
so I just tried to squash the commits, but I am not sure it likes it.

**Pull request merged**
