### PR TITLE
bump version wasmd to hot fix bugs

### PR DESCRIPTION
**Pull request by hoank101**
## Description and Motivation
bump version wasmd to hot fix bugs 

## Related Issues

https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-004.md

---
## Checklist:

- [ ] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-chain/blob/main/docs/CONTRIBUTING.md).
- [ ] My pull request has a sound title and description (not something vague like `Update index.md`)
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation.
- [ ] The code is formatted properly `golangci-lint run ./... --fix`.

### CODE REVIEW

**Comment by hoank101** [comment]
hi @faddat please review it

**Comment by faddat** [comment]
Reviewing now

**Review by faddat — APPROVED** [review]
Approving provisionally -- I didn't know that they released a v1.2.x wasmvm?

But if so, great, and thanks for chasing down the changes in that ancient fork

**Comment by faddat** [comment]
Merging.  Please make sure that we have deploy directives at the ready.

**Comment by hoank101** [comment]
> Approving provisionally -- I didn't know that they released a v1.2.x wasmvm?
> 
> But if so, great, and thanks for chasing down the changes in that ancient fork

They just released -> https://github.com/CosmWasm/wasmvm/releases/tag/v1.2.5

**Pull request merged**
