### PR TITLE
[reviewing] patch white whale for 2 newly disclosed bugs

### PR DESCRIPTION
**Pull request by faddat**
## Related Issues

---
## Checklist:

- [ ] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-chain/blob/main/docs/CONTRIBUTING.md).
- [ ] My pull request has a sound title and description (not something vague like `Update index.md`)
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation.
- [ ] The code is formatted properly `golangci-lint run ./... --fix`.

### CODE REVIEW

**Comment by duvbell** [comment]
I updated logic for the patch to work, and added the encoding scheme for `generating packet` in the `ica test`.

**Comment by duvbell** [comment]
@faddat please  review this?

**Comment by faddat** [comment]
yep

**Comment by faddat** [comment]
@kienn6034 I approve, but need two reviewers who aren't me to approve it, since I started the PR.

🖖

**Review by hoank101 — APPROVED** [review]
LGTM

**Review by 0xFable — APPROVED** [review]

**Pull request merged**
